sonar.projectKey=venta-express_millionaire-project
sonar.organization=venta-express
sonar.projectName=proyecto millonario
sonar.sources=.
sonar.tests=tests
sonar.exclusions=**/__pycache__/**,**/*.pyc,**/*.pyo,tests/**
sonar.python.coverage.reportPaths=coverage.xml
sonar.python.version=3.13
