sonar.projectKey=venta-express_millionaire-project
sonar.organization=venta-express
sonar.projectName=proyecto millonario
sonar.sources=.
sonar.exclusions=**/__pycache__/**,**/*.pyc,**/*.pyo,ui/**
sonar.python.version=3.11
sonar.python.coverage.reportPaths=coverage.xml
sonar.coverage.exclusions=ui/**,utils/styles.py,utils/constants.py,main.py,db/connection.py
